#!/usr/bin/env bash
#
#############################################################################
#############################################################################
#
# bake: a complete and deterministic environment for the standard upstream
#           build and compose tools (koji/pungi/livecd-creator)
#
#############################################################################
#
# Copyright 2007-2011 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of X.
#
#    X is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    X is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with X.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
# note: if you'd like a different license, just let me know which and why
#############################################################################


#############################################################################
#############################################################################
##
## bake
##
##
## DESCRIPTION
##
## bake takes as input network or offline access to a bootstrapping
## enterprise linux distro (e.g. SL60/F13) and recently built set of distro
## packages (e.g. from koji), and outputs a new installable distro repotree
## (e.g. ASC60) suitable for mirroring to the masses.
##
##
## LONG TERM ROADMAP
##
## - the input pipeline will be expanded to include:
##  - use gen-tdv-srpm-repos to create the input srpms from the dev/git tree
##  - invoking makeworld/koji to generate what is the current input
##
##
## NOTES
##
## - output reproducibility is ensured by the fact that a disposable VM
##   is generated and used for the major processing phases (e.g. pungi,
##   and later koji).
##
## - el-build host requirements (or, what the devoloper has)
##  - x86_64 2 core system, 4G of ram
##  - 200G tmp disk space, 30G for final output
##
#############################################################################


#############################################################################
#############################################################################
##
## TODO
# - factor main into several large independent functions, 1 per bake phase
# - add option bootstrap_distro_tree=...sl60x64
#  - and in general factor all configuration into proper configuration
# - ...
#


#############################################################################
#############################################################################
##
## local constant definitions
##

# for common script library- libx.sh
x_toolname="el-build"
x_prefix=/usr


#############################################################################
#############################################################################
##
## load system library
##

if [ -f "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh" ]; then
    source "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh"
elif [ -f "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" ]; then 
    source "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" 
else
    echo "$0: error: fatal: could not load ${x_toolname} system library libx.sh"
    exit 1
fi


#############################################################################
#############################################################################
##
## constant and option default definitions
##

builtrepo_def="${x_bake_builtrepo}"
distroname_def="${x_bake_distroname}"
distrover_def="${x_bake_distrover}"
offline_def="${x_bake_offline}"
do_bake_phases_def="${x_bake_do_bake_phases}"
bake_flags_def="${x_bake_bake_flags}"
test_package_list_def="${x_bake_test_package_list}"
distrorelname_def="${x_bake_distrorelname}"
# presumption is to first check in ./, then x_devdir/6/distrover/
config_x64_def="${x_bake_config_x64}"
config_x32_def="${x_bake_config_x32}"
outputdir_def="${x_bake_outputdir}"
homedotdir_def="${x_bake_homedotdir}"
cachedir_def="${x_bake_cachedir}"
bake_tmpdir_def="${x_bake_tmpdir}"
clear_bootstrapos_repodata_def="${x_bake_clear_bootstrapos_repodata}"

# a rather internally hardcoded list for the first pass
# TODO: add a method for specifying a mirror to use if desired for any entry
mirror_dirs="\
ftp://ftp.scientificlinux.org/linux/scientific/6x/SRPMS
ftp://ftp.scientificlinux.org/linux/scientific/6.0/x86_64/os
ftp://ftp.scientificlinux.org/linux/scientific/6.0/i386/os
http://build.ascendos.org/linux/ascendos/SRPMS
http://build.ascendos.org/linux/ascendos/6.0
"

pigz_version="2.1.6-1"
mock_version="1.1.15-1"
livecdtools_version="13.4-1"

# another hardcoded internal list
mirror_files="\
ftp://ftp.linux.ncsu.edu/pub/fedora/linux/releases/13/Everything/i386/os/RPM-GPG-KEY-fedora-13-primary
ftp://ftp.linux.ncsu.edu/pub/fedora/linux/releases/13/Everything/source/SRPMS/python-kid-0.9.6-6.fc13.src.rpm
ftp://ftp.linux.ncsu.edu/pub/fedora/linux/releases/13/Everything/source/SRPMS/repoview-0.6.5-1.fc13.src.rpm
ftp://ftp.linux.ncsu.edu/pub/fedora/linux/releases/13/Everything/source/SRPMS/pungi-2.0.21-1.fc13.src.rpm
ftp://ftp.linux.ncsu.edu/pub/fedora/linux/updates/13/SRPMS/zyx-liveinstaller-0.2.4-1.fc13.src.rpm
ftp://ftp.linux.ncsu.edu/pub/epel/RPM-GPG-KEY-EPEL-6
ftp://ftp.linux.ncsu.edu/pub/epel/6/SRPMS/pigz-${pigz_version}.el6.src.rpm
ftp://ftp.linux.ncsu.edu/pub/epel/6/SRPMS/mock-${mock_version}.el6.src.rpm
ftp://ftp.linux.ncsu.edu/pub/epel/6/SRPMS/livecd-tools-${livecdtools_version}.el6.src.rpm
"

# to enable debug messages if desired
x_debug=1

# to suppress status messages if desired
x_quiet=0


#############################################################################
#############################################################################
##
## functions
##
function usage {
    echo ""
    echo "usage:"
    echo ""
    echo "${progname} \\"
    echo "    [distroname=${distroname_def}] \\"
    echo "    [distrover=${distrover_def}] \\"
    echo "    [offline=${offline_def}] \\"
    echo "    [do_bake_phases=${do_bake_phases_def}] \\"
    echo "    [bake_flags=${bake_flags_def}] \\"
    echo "    [test_package_list=${test_package_list_def}] \\"
    echo "    [distrorelname=${distrorelname_def}] \\"
    echo "    [config_x64=${config_x64_def}] \\"
    echo "    [config_x32=${config_x32_def}] \\"
    echo "    [outputdir=${outputdir_def}] \\"
    echo "    [cachedir=${cachedir_def}] \\"
    echo "    [bake_tmpdir=${bake_tmpdir}_def}] \\"
    echo "    [builtrepo=${builtrepo_def}]"
    echo ""
    echo "All arguments are optional, with default values shown as above."
    echo ""
    echo "some development/debug options are-"
    echo "    [clear_bootstrapos_repodata=${clear_bootstrapos_repodata_def}]"
    echo ""
    echo ""
    exit 1
}


#############################################################################
#############################################################################
##
## main
##

status "initializing..."


# note: presumption is that el-build is run from within it's own
#       developtment tree, e.g. 
# $ ./relative/path/to/Ascendos/tools/el-build/el-build or $ ./el-build

#############################################################################
#
## set option value defaults
#
distroname="${distroname_def}"
distrover="${distrover_def}"
offline="${offline_def}"
do_bake_phases="${do_bake_phases_def}"
bake_flags="${bake_flags_def}"
test_package_list="${test_package_list_def}"
clear_bootstrapos_repodata="${clear_bootstrapos_repodata}"
distrorelname="${distrorelname_def}"
config_x64="${config_x64_def}"
config_x32="${config_x32_def}"
outputdir="${outputdir_def}"
homedotdir="${homedotdir_def}"
cachedir="${cachedir_def}"
bake_tmpdir="${bake_tmpdir_def}"
builtrepo="${builtrepo_def}"


#############################################################################
#
## process command line arguments / options
#
status "processing options..."
# this is a simple enough method for a first pass.  I'd have brought in
# viros's libvopt.sh if it wasn't so complex.
for option in "$@"; do
    if [ "${option}" == "usage" ]; then
	usage
    elif [ "${option}" == "--usage" ]; then
	usage
    elif [ "${option}" == "help" ]; then
	usage
    fi
    if $( echo "${option}" | grep -q "=" ); then
	# simplest
#	eval "${option}"
	# a bit better, allows e.g. distroname="Two Words"
	# (though a two word distroname is as yet untested and may not work anyway)
	opt_name=$( echo "${option}" | sed -e 's/=.*//' )
	opt_val=$( echo "${option}" | sed -e 's/[^=]*=//' )
	eval "${opt_name}='${opt_val}'"
    else
	status "option '${option}' is invalid, options must be of the form 'option_name=option_value'"
	usage
    fi
    debug "opt is $option"
done


# todo: fill out list or get more abstract (ala viros' libvopt.sh)
#status "outputdir is ${outputdir}"
#status "distroname is ${distroname}"

if ( ! mkdir -p "${outputdir}" > /dev/null 2>&1 ); then
    die "output directory - ${outputdir} - could not be made"
fi

bvm_tmpdir="${bake_tmpdir}/${starttime}.${mypid}.vm"
if ( ! mkdir -p "${bvm_tmpdir}" > /dev/null 2>&1 ); then
    die "temp directory - ${bvm_tmpdir} - could not be made"
fi


#############################################################################
#
## clean stale state from prior runs
#

status "cleaning away residue from prior cooks ..."

num_bakers=$( virsh list --all \
    | awk '{print $2}' \
    | grep "^bake" \
    | wc -l )

num_stale_bakes=$( \
    echo "${num_bakers} - ${x_keep_old_baker_vm_definitions}" \
    | bc -l )

stale_bakes=$( virsh list --all \
    | awk '{print $2}' \
    | grep "^bake" \
    | sort \
    | head "-${num_stale_bakes}" )

for stale_bake in ${stale_bakes}; do

    status "saving xml for stale bake vm ${stale_bake} ..."
    virsh \
	dumpxml \
	"${stale_bake}" \
	> "${bvm_tmpdir}/.stale.baker_vm.${stale_baker}.xml" 2>&1

    status "undefining stale bake vm ${stale_bake} ..."
    virsh \
	undefine \
	"${stale_bake}" \
	> "${bvm_tmpdir}/.stale.baker_vm.${stale_baker}.undef.log" 2>&1

done

#############################################################################
#
## update mirrors / cache
#
status "updating cache / mirrors..."

# TODO: build.a.o needs to be mirrored, and thus de-referenced here
#       (due to bandwidth use, etc...)

# TODO: the bootstrapping OS needn't be full mirrored
#       (a script to mirror the needed parts of a repo from a .ks
#        would be very appreciated.  hint hint)

# use lftp for mirroring

# note: perhaps? pull instead from koji, or ascendos/everything 
#       (based on binary rpm name list generated from tuv srpm list)


if ( ! mkdir -p "${cachedir}" > /dev/null 2>&1 ); then
    die "cache directory (mirror root) - ${cachedir} - could not be used/made"
fi

cd "${cachedir}"

# TODO: support rsync as an option

if [ "${clear_bootstrapos_repodata}" == "yes" ]; then
    status "clearing out cached bootstrap OSs repodata"
    # pretty ugly workaround for some issue probably resolved by a prior bugfix, but
    # just in case it happens again, a reminder option.
    rm -rf ./ftp.scientificlinux.org___linux__scientific__6.0__i386__os/repo{data,view}
    rm -rf ./ftp.scientificlinux.org___linux__scientific__6.0__x86_64__os/repo{data,view}
    rm -rf ./ftp.scientificlinux.org___linux__scientific__6x__SRPMS/repo{data,view}
fi

if [ "${offline}" == "yes" ]; then
    status "offline mode: not updating cache / mirrors..."
else

    if ( ! ping -c3 mirrors.kernel.org > /dev/null 2>&1 ) then
        # presume offline intent if no net connection seemingly present
	status "can't ping mirrors.kernel.org, falling back to trying an offline from-cache build ..."
	offline=yes
    else
	# this should get factored into its own function/script

	for mirror_dir in ${mirror_dirs}; do
	    status "updating mirror: ${mirror_dir}"
	    
	    mirror_hostpath=$( echo "${mirror_dir}" | sed -e 's/[^\/]*\/\///' )
	    debug "mirror_hostpath is ${mirror_hostpath}"
	    mirror_urltype=$( echo "${mirror_dir}" | sed -e 's/:\/\/.*//' )
	    debug "mirror_urltype is ${mirror_urltype}"
	    mirror_host=$( echo "${mirror_hostpath}" | sed -e 's/\/.*//' )
	    debug "mirror_host is ${mirror_host}"
	    mirror_path=$( echo "${mirror_hostpath}" | sed -e 's/[^\/]*\///' )
	    debug "mirror_path is ${mirror_path}"
	    mirror_path_parent=$( dirname "${mirror_path}" )
	    debug "mirror_path_parent is ${mirror_path_parent}"
	    mirror_path_child=$( basename "${mirror_path}" )
	    debug "mirror_path_child is ${mirror_path_child}"
	    mirror_path_xmog=$( echo "${mirror_path}" | sed -e 's/\//__/g' )
	    mirror_dir_xmog="${mirror_host}___${mirror_path_xmog}"
	    debug "mirror_dir_xmog is ${mirror_dir_xmog}"

	    mirror_dest_path="${cachedir}/${mirror_dir_xmog}"
	    if ( ! mkdir -p "${mirror_dest_path}" > /dev/null 2>&1 ); then
		die "could not mkdir ${mirror_dest_path}"
	    fi
	    
	    lftp -e "cd ${mirror_path_parent} ; mirror --parallel=2 --use-cache --ignore-time --continue --delete ${mirror_path_child} ${mirror_dest_path}; quit" "${mirror_urltype}://${mirror_host}"
	    
	done
	
	mkdir -p "${cachedir}/one-off-files"
	for mirror_file in ${mirror_files}; do
	    status "caching file: ${mirror_file}"
	    
	    mirror_hostpath=$( echo "${mirror_file}" | sed -e 's/[^\/]*\/\///' )
	    debug "mirror_hostpath is ${mirror_hostpath}"
	    mirror_urltype=$( echo "${mirror_file}" | sed -e 's/:\/\/.*//' )
	    debug "mirror_urltype is ${mirror_urltype}"
	    mirror_host=$( echo "${mirror_hostpath}" | sed -e 's/\/.*//' )
	    debug "mirror_host is ${mirror_host}"
	    mirror_path=$( echo "${mirror_hostpath}" | sed -e 's/[^\/]*\///' )
	    debug "mirror_path is ${mirror_path}"
	    mirror_path_parent=$( dirname "${mirror_path}" )
	    debug "mirror_path_parent is ${mirror_path_parent}"
	    mirror_path_child=$( basename "${mirror_path}" )
	    debug "mirror_path_child is ${mirror_path_child}"
	    mirror_path_xmog=$( echo "${mirror_path}" | sed -e 's/\//__/g' )
	    mirror_file_xmog="${mirror_host}___${mirror_path_xmog}"
	    debug "mirror_file_xmog is ${mirror_file_xmog}"
	    
            # for now, just clobber
            # TODO: have finer grained actual caching behavior
	    rm -f "${cachedir}/one-off-files/${mirror_path_child}"
	    wget -q -O "${cachedir}/one-off-files/${mirror_path_child}" \
		"${mirror_file}"
	    
	done

        # note: ugly(?) temporary workaround that will be obsolete no later than the 
        #       time when koji/makeworld show up in el-build
        # todo: handle packaged installed case, i.e. not x_devdir relative, but... (and elsewhere)
	createrepo \
	    "${cachedir}/build.ascendos.org___linux__ascendos__SRPMS"
	createrepo \
	    -g "${x_devdir}/6/6.0/configs/comps-asc6-x86_64.xml" \
	    "${cachedir}/build.ascendos.org___linux__ascendos__6.0/os/x86_64" 
	createrepo \
	    -g "${x_devdir}/6/6.0/configs/comps-asc6-i386.xml" \
	    "${cachedir}/build.ascendos.org___linux__ascendos__6.0/os/i386" 

        ## create multiarch repo structure usable by koji
        # TODO: total temporary hack, long term the first thing that comes to mind
        #       is having this mirroring code, seperated out into a seperate script,
        #       and using a config file for target directories, and encoding effectively
        #       the entire url (including scheme, e.g. rsync/http/ftp) and target directory.
        #       I.e. an evolution beyond what viros' does with vmirmog to resolve the 
        #       issue of making it simple to seperate the phases of 'pull stuff from net'
        #       and 'convert that stuff to the output'.
        mkdir -p \
    	    "${cachedir}/ftp.scientificlinux.org___linux__scientific__6.0"
	mkdir -p \
	    "${cachedir}/ftp.scientificlinux.org___linux__scientific__6.0/i386"
	mkdir -p \
	    "${cachedir}/ftp.scientificlinux.org___linux__scientific__6.0/x86_64"
	ln -s \
	    ../../ftp.scientificlinux.org___linux__scientific__6.0__i386__os \
	    "${cachedir}/ftp.scientificlinux.org___linux__scientific__6.0/i386/os"
	ln -s \
	    ../../ftp.scientificlinux.org___linux__scientific__6.0__x86_64__os \
	    "${cachedir}/ftp.scientificlinux.org___linux__scientific__6.0/x86_64/os"
    fi

fi

# trust our own copies of the keys, instead of theoretical mitm 
# during the download of the src.rpms from the same server
cp "${x_devdir}/security/keys/RPM-GPG-KEY-"* \
    "${cachedir}/one-off-files/"


#############################################################################
#
## launch user-httpd on port 8421
#

# TODO: use random port between some range instead of static port

# note: one could also tar up the docroot into a new qemu disk image, and
#       use that to expose the data to the VM (or probably several other
#       ways, including non-userstack networking that may be faster)

# create directory for config/logs, and one for docroot
mkdir -p "${homedotdir}/vm-httpd/${starttime}.${mypid}.etc"
mkdir -p "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot"

# expose the mirrors / cache inside the docroot
ln -s ../../cache \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/cache"

status "launching user (non-root) httpd as a service for the inner processing vm ..."
# TODO: this should no doubt be narrowed, lazy big hammer for the first pass
killall httpd > /dev/null 2>&1
sleep 2
killall -KILL httpd > /dev/null 2>&1
sleep 2
# launch the httpd daemon
user-httpd \
    "${x_builder_user_httpd_port}" \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot" \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.etc" \
    start


#############################################################################
#
## prepare network environment for the throwaway vm
#

if [ "${do_bake_phases}" == "all" ]; then
    do_bake_phases="\
compile-sources
installer-traditional-x32
installer-traditional-x64
installer-live-x32
installer-live-x64
stage-layout
"
fi

# support both space and comma seperated lists as input for do_bake_phases
new_bake_phases=""
for bake_phase in $( echo "${do_bake_phases}" ); do
    new_bake_phases="${new_bake_phases} $( echo ${bake_phase} | sed -e 's/,/ /g' )"
done
do_bake_phases="${new_bake_phases}"

# support both space and comma seperated lists as input for do_bake_phases
new_list=""
for test_package in $( echo "${test_package_list}" ); do
    new_list="${new_list} $( echo ${test_package} | sed -e 's/,/ /g' )"
done
testing_package_list="${new_list}"

# expose baking options to the inner/v-bake script
# TODO: probably a cleaner way
# ?: will this even work, or will multiline above cause problems?
cat <<EOF > "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/v-bake.options" 
do_bake_phases="${do_bake_phases}"
bake_flags="${bake_flags}"
test_package_list="${test_package_list}"
EOF

# todo: make the list of vars a list and iterate here and above
export do_bake_phases
export bake_flags
export test_package_list

debug "do_bake_phases option being passed to v-bake is: ${do_bake_phases} ..."
debug "bake_flags option being passed to v-bake is: ${bake_flags} ..."

## expose inner processing script (x-run/v-bake) in the docroot
cp "${x_devdir}/tools/scripts/v-bake" \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/x-run" 

## expose kickstarts for pungi and livecd-creator in the docroot
cp "${x_devdir}/6/6.0/configs/"*.ks \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/" 

## expose pungi i386 mock config in the docroot
cp "${x_devdir}/6/6.0/configs/mock-"*.cfg \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/" 


### create throwaway vm's .ks from template, placed in docroot
cp "${x_devdir}/${x_builder_vm_kickstart}" \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/baker.ks" 

status "preparing a full copy of the build tools devtree for the inner-vm to use ..."
### give a full copy of the devtree to the vm
tar -C $( dirname "${x_devdir}" ) -cjf \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/devtree.tar.bz2" \
    $( basename "${x_devdir}" )

#############################################################################
#
## processing container/vm kickstart additions (to a minimal kickstart)
#
cat <<EOF >> "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/baker.ks"
%packages --default
# for retrieving files from the host httpd server and/or the internet
wget
%end

%post --log=/root/min-ks.post.log.log

# 1G of swapfile
dd if=/dev/zero of=/.swapfile bs=1M count=1024 2>&1 | tee -a /var/log/mkswap.log
mkswap /.swapfile 2>&1 | tee -a /var/log/mkswap.log

## services
/sbin/chkconfig --level=3 NetworkManager


#############################################################################
#
## rc.local appending: executed _AFTER_ install, on first boot
#
cat << FOO >> /etc/rc.d/rc.local

# disable selinux enforcement for makeworld/koji/pungi
setenforce 0

# enable swapfile
swapon /.swapfile

# let the user see terminal output if they happen to be watching a console
rhgb-client --quit
# disable console blanking since this will be a VM, not a real monitor
setterm -blank 0

# only do x-run once, not every boot
if [ ! -f /root/x-run ]; then

    # tell x-run that it is OK to overwrite /dev/sdb with its output
    touch /tmp/disk-sdb-is-going-to-get-overwritten

    # pull task to run from qemu-kvm host running el-build spawned httpd on port 8421
    wget -O /root/x-run http://10.0.2.2:8421/x-run
    chmod +x /root/x-run
    # TODO: x-run uses the installed yum.repos.d, which do not yet utilize
    #       available mirrors (cough, vmirmog, cough)
    ( ( /root/x-run ; init 0 ) 2>&1 | tee -a /root/x-run.log ) &
fi

FOO
#
## end post-install rc.local appendage
#
#############################################################################

%end
EOF

#
## end processing container/vm kickstart additions
#
#############################################################################

#############################################################################
#
## processing target distro output kickstart (for pungi)
#

# nothing dynamic yet, put probably sooner or later
sed -i \
    -e 's/example/example/g' \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/${config_x64}" 
sed -i \
    -e 's/example/example/g' \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/${config_x32}" 

#
## end processing target distro output kickstart (for pungi)
#
#############################################################################

# TODO perhaps improve with definable/option for bootstrap_repotree
# TODO more general/flexible mirror support ala viros' vmirmog etc...  (too complex for now)
sed -i \
    -e 's|ftp://ftp.scientificlinux.org/linux/scientific/6.0/x86_64/os|http://10.0.2.2:8421/cache/ftp.scientificlinux.org___linux__scientific__6.0__x86_64__os|' \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/baker.ks"


#############################################################################
#
## create throwaway vm disk image
#

status "creating new system disk image files for the inner-vm ..."
# TODO: x_eval wrapper for logging (ala viros' 'veva' function)
qemu-img create \
    "${bvm_tmpdir}/sysroot.img" \
    "${x_builder_vm_root_fs_size}" \
    >> "${bvm_tmpdir}/qemu-img-create.log" 2>&1

qemu-img create \
    "${bvm_tmpdir}/output.img" \
    "${x_builder_vm_output_fs_size}" \
    >> "${bvm_tmpdir}/qemu-img-create.log" 2>&1

qemu-img create \
    "${bvm_tmpdir}/scratch.img" \
    "${x_builder_vm_scratch_fs_size}" \
    >> "${bvm_tmpdir}/qemu-img-create.log" 2>&1


#############################################################################
#
## check for cached copy of throwaway vm
#

# see if cached copy exists by calculating filename based on sha256 checksum
vm_cfg_checksum=$( sha256sum \
    "${homedotdir}/vm-httpd/${starttime}.${mypid}.docroot/baker.ks" \
    | awk '{print $1}')

if [ -f "${cachedir}/vm-${vm_cfg_checksum}.img" ]; then

    status "found acceptable cached system image, duplicating ..."

    rm -f "${bvm_tmpdir}/sysroot.img"

    cp -a --sparse=always \
	"${cachedir}/vm-${vm_cfg_checksum}.img" \
	"${bvm_tmpdir}/sysroot.img"

    touch "${bvm_tmpdir}/sysroot.img.fromcache"

    virt-install \
	--import \
	--name="${progname}-${starttime}-${mypid}" \
	--disk="${bvm_tmpdir}/sysroot.img" \
	--disk="${bvm_tmpdir}/output.img" \
	--disk="${bvm_tmpdir}/scratch.img" \
	--ram="${x_builder_vm_memory}" \
	--noreboot \
	--wait=-1 \
	--noautoconsole \
	-x "ks=http://${x_builder_vm_host_ip}:${x_builder_user_httpd_port}/baker.ks" \
	> "${bvm_tmpdir}/virt-install.log" 2>&1

else

#############################################################################
#
## run netinst(all) on/to throwaway vm disk image
#

# TODO: add standard qemu (not provided by tuv's repos) as fallback for
#       an x32 build option, or e.g. my amd-sempron3400+ no-amd-svm case

# TODO: is the root of security/pristineness here that the locally cached
#       copy of the pungi-bootstrap os was not corrupt?  I.e. perhaps add
#       some sort of check against our copy of hashes for the files used
#       for the netinst here (just boot.iso? or does virt-install pull the
#       kernel and initrd from PXE/pxeboot directories?)

# TODO: make --noautoconsole a --quiet/--debug/--verbose kind of thing

    status "launching inner-vm installation (domain:${progname}-${starttime}-${mypid}) ..."
    status "note: use 'el-build view-last-bake-vm' to get a console view of the installation ..."
    virt-install \
	--name="${progname}-${starttime}-${mypid}" \
	--location="${cachedir}/ftp.scientificlinux.org___linux__scientific__6.0__x86_64__os" \
	--disk="${bvm_tmpdir}/sysroot.img" \
	--disk="${bvm_tmpdir}/output.img" \
	--disk="${bvm_tmpdir}/scratch.img" \
	--ram="${x_builder_vm_memory}" \
	--noreboot \
	--wait=-1 \
	--noautoconsole \
	-x "ks=http://${x_builder_vm_host_ip}:${x_builder_user_httpd_port}/baker.ks" \
	> "${bvm_tmpdir}/virt-install.log" 2>&1


    # cache a pristine copy for future runs
    # note: could use qemu-img or other snapshots, but those may have performance issues
    status "stashing a duplicate of the freshly installed vm in the cache ..."
    cp -a --sparse=always \
	"${bvm_tmpdir}/sysroot.img" \
	"${cachedir}/vm-${vm_cfg_checksum}.img"
fi


#############################################################################
#
## run throwaway vm for main/inner processing/build phase
#

## todo: have all virt runs log through simple text channel to console, i.e.
##       console over serial port, or ssh/netcat logfile streaming...

status "saving inner-vm's virtualization domain information ..."
virsh \
    dumpxml \
    "${progname}-${starttime}-${mypid}" \
    > "${bvm_tmpdir}/vdomain.xml"

status "launching inner-vm's processing phase ..."
virsh \
    start \
    "${progname}-${starttime}-${mypid}" \
    > "${bvm_tmpdir}/virt-run.log" 2>&1

status "waiting a few seconds for inner-vm to come online ..."
sleep 24

# TODO: make this a --debug only thing
status "debug/viewing inner-vm console ..."
view-last-bake-vm &

status "waiting for inner-vm to finish processing ..."
# wait until processing is complete
xdone=0
while ((! ${xdone})); do
    sleep "${x_builder_vm_shutdown_polling_frequency}"
    if $( ! virsh list | grep "${progname}-${starttime}-${mypid}" | grep -q running ); then
	xdone=1
    fi
done


#############################################################################
#
## arrange output for user, clean up, and exit
#

status "arranging output for the user ..."
tar \
    -C "${outputdir}" \
    -xvf "${bvm_tmpdir}/output.img"

status "cleaning up ..."

# leave it around for development/debugging, it'll get cleaned out
# by a subsequent run (see x_keep_old_baker_vm_definitions default)
#virsh \
#    undefine \
#    "${progname}-${starttime}-${mypid}"


status "done."
exit 0

#############################################################################
## end script - only notes below
#############################################################################
#
#
#

