#!/bin/bash

#
# el-build system options
#

# how much memory to use for installing and running the 
# el-build processing vm host
x_builder_vm_memory=768

# not really variable, could be moved elsewhere
x_builder_vm_host_ip=10.0.2.2

# this should be made dynamic at runtime between a specified range
x_builder_user_httpd_port=8421

# seconds between checks to see if processing in the vm completed
x_builder_vm_shutdown_polling_frequency=30


