#!/usr/bin/env bash
#
#############################################################################
#############################################################################
#
# hello-world: a template el-build subcommand script
#
#############################################################################
#
# Copyright 2007-2011 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of X.
#
#    X is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    X is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with X.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
# note: if you'd like a different license, just let me know which and why
#############################################################################


#############################################################################
#############################################################################
##
## hello-world
##
##
## DESCRIPTION
##
## just a template to use for building new el-build subcommands with bash
##
##
#############################################################################


#############################################################################
#############################################################################
##
## local constant definitions
##

# for common script library- libx.sh
x_toolname="el-build"
x_prefix=/usr


#############################################################################
#############################################################################
##
## load system library
##

if [ -f "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh" ]; then
    source "$( dirname $( readlink -e $0 ) )/../../tools/scripts/libx.sh"
elif [ -f "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" ]; then 
    source "${x_prefix}/lib/${x_toolname}/scripts/libx.sh" 
else
    echo "$0: error: fatal: could not load ${x_toolname} system library libx.sh"
    exit 1
fi


#############################################################################
#############################################################################
##
## constant and option default definitions
##

# to enable debug messages if desired
x_debug=0

# to suppress status messages if desired
x_quiet=0


#############################################################################
#############################################################################
##
## functions
##
function usage {
    echo ""
    echo "usage:"
    echo ""
    echo "${progname} \\"
    echo "    [command options...]"
    echo ""
    echo ""
    exit 1
}


#############################################################################
#############################################################################
##
## main
##

status "initializing..."

# if it doesn't appear we are online, presume the intent is an offline
# from cached sources run, otherwise, update caches
if ( ping -c3 mirrors.kernel.org > /dev/null 2>&1 ); then
    status "mirroring upstream sources"
    mirror-tuv-srpms-el6
else
    status "system seems offline, generating big board from cached sources ..."
fi

status "sorting upstream sources by build date"
datesort-tuv-el6-srpms

status "generating initial spreadsheet"
repochart-tuv-el6

status "correlating data with compile/build server buildinfo"
bs-check-tuv-el6

status "big board generation done: output is likely here-"
status "${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise.6Superset.en.os.SRPMS.bsinfochart.html"

#############################################################################
## end script - only notes below
#############################################################################
#
#
#
