#!/usr/bin/env bash
#
#############################################################################
#############################################################################
#
# src-pkg-repo-diff--gen-min-srpm-list (a first phase)
#
#
# src-pkg-repo-diff generates a set of abbreviated comparisons of two 
#                   related source package (src.rpm) repositories.
#
#############################################################################
#
# Copyright 2011 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of X.
#
#    X is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    X is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with X.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
# note: if you'd like a different license, just let me know which and why
#############################################################################


#############################################################################
#############################################################################
##
## src-pkg-repo-diff--gen-min-srpm-list \
##     [<output_file>=<input_right>.repo-diff.srpm-list] \
##     [[<input_left>=${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise/6Superset/en/os/SRPMS] \
##     [<input_right>=${HOME}/.el-build/cache/build.ascendos.org___linux__ascendos__SRPMS]]
##
##
## DESCRIPTION
##
## ...
##
##
## NOTES
##
## - input_left and _right must both be specified if at all
##
#############################################################################

## TODO
# - ...
#  - all very hardcoded for initial asc workflow, improve flexibility/utility
#  - definitely should support diffing sl6/etc... as well against tuv, for
#    sanity comparison and reference value


#############################################################################
#############################################################################
##
## get runtime environment
##
starttime="$( date +%Y-%m-%d--%H-%M-%S )"
progname="$( basename $0 )"
progdir=$( ( pushd $( dirname $( readlink -e $0 ) ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )
rundir="$( pwd )"
mypid=$$


#############################################################################
#############################################################################
##
## constant and option default definitions
##

# to enable debug messages
debug=1

# to suppress status messages
quiet=0


#############################################################################
#############################################################################
##
## functions
##
function usage {
    echo ""
    echo "usage:"
    echo ""
    echo "${progname} ... (TODO/FIXME)"
    echo ""
    echo ""
    exit 1
}


#############################################################################
#
# usage: status <message...>
#
# wrapper for sending status messages to console and log
#
# globals used: quiet, progname, logfiles(not required)
#
function status {
    time="$( date +%Y-%m-%d.%H:%M:%S )"
    if ((! $quiet)); then
	echo "${progname}: ${time}: status: $@"
    fi
    for logfile in $logfiles; do
	echo "${progname}: ${time}: status: $@" >> $logfile
    done
}

#############################################################################
#
# usage: debug <message...>
#
# wrapper for sending debug messages to console and log
#
# globals used: debug, progname, logfiles(not required)
#
function debug {
    time="$( date +%Y-%m-%d.%H:%M:%S )"
    if (($debug)); then
	echo "${progname}: ${time}: debug: $@"
    fi
    for logfile in $logfiles; do
	echo "${progname}: ${time}: debug: $@" >> $logfile
    done
}


#############################################################################
#
# usage: die <message...>
#
# issue last words
#
function die {
    status "$@"
    exit 1
}


#############################################################################
#
# usage: listremove "item" "list"
#
# return a list copy but with an item taken out
#
function listremove {
    item="${1}"
    shift

    for word in ${@}; do
	if [ "${word}" != "${item}" ]; then
	    echo -en "${word} "
	fi
    done
}


#############################################################################
#
# usage: listin "item" "list"
#
# return true if item is in list
#
function listin {
    item="${1}"
    shift

    retval=false
    for word in "$@"; do
	if [ "${word}" == "${item}" ]; then
	    return 0;
	fi
    done
    return 1
}


#############################################################################
#
# usage: listreverse "list"
#
# returns a given list of words reversed
#
function listreverse {
    numwords=0
    for word in $@; do
	numwords=$(( ${numwords} + 1 ))
	wordlist[${numwords}]="${word}"
    done
    for (( i=numwords ; ${i} > 0 ; i=$(( ${i} - 1 )) )); do
	echo "${wordlist[${i}]}"
    done
}


#############################################################################
#
# usage: get_asc_version <some-version.asc[.ASCVERSION].src.rpm>
#
# dies if input is not a proper .asc[.ASCVERSION].src.rpm, and returns
# ASCVERSION, or the special 0 value for no suffixed version
#
function get_asc_version {
    if ( echo "$@" | grep -q "\.asc\.src\.rpm$" ); then
	echo 0
    elif ( ! echo "$@" | grep -q "\.asc\.[0-9]*\.src\.rpm$" ); then
	die "no asc version because $@ is not a .asc.*src.rpm"
    else
	echo "$@" | sed -e 's/.*\.asc\.\([0-9]*\)\.src\.rpm$/\1/'
    fi
}


#############################################################################
#
# usage: set_asc_version <version> <some-version.asc[.ASCVERSION].src.rpm>
#
# returns the given asc style package name, but with alternate version
#
function set_asc_version {
    version="${1}"
    shift

    if ( ! echo "$@" | grep -q "\.asc\.src\.rpm$" ); then
	if ( ! echo "$@" | grep -q "\.asc\.[0-9]\+\.src\.rpm$" ); then
	    die "set_asc_version: non-well-formatted asc src rpm file: $@"
	fi
    fi

    if ((!${version})); then
	if ( echo "$@" | grep -q "\.asc\.src\.rpm$" ); then
	    # in this case, return the same as the input
	    echo "$@"
	else 
	    echo "$@" | sed -e "s/\.asc\.[0-9]\+\.src\.rpm\$/\.asc\.src\.rpm/"
	fi
    else
	if ( echo "$@" | grep -q "\.asc\.src\.rpm$" ); then
	    echo "$@" | sed -e "s/\.asc\.src\.rpm\$/\.asc\.${version}\.src\.rpm/"
	else
	    echo "$@" | sed -e "s/\.asc\.[0-9]\+\.src\.rpm\$/\.asc\.${version}\.src\.rpm/"
	fi
    fi
}


#############################################################################
#
# usage: old_school_crypto <string>
#
# probably overkill avoidance of explicit TUV referencing
#
function old_school_crypto {
    echo "$@" | tr 'a-zA-Z' 'n-za-mN-ZA-M'
}


#############################################################################
#############################################################################
##
## main
##

status "initializing..."


#############################################################################
### calculate tree root and set up environment
elbuild_devroot=$( pushd "${progdir}/../.." > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 )


#############################################################################
### retrieve arguments/options
if [ $# -eq 0 ]; then 
    input_left=$( readlink -e "${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise/6Superset/en/os/SRPMS" )
    input_right=$( readlink -e "${HOME}/.el-build/cache/build.ascendos.org___linux__ascendos__SRPMS" )
    output_file=${input_right}.repo-diff.srpm-list
elif [ $# -eq 1 ]; then 
    output_file=$( readlink -f "${1}" )
    input_left=$( readlink -e "${HOME}/.el-build/cache/ftp.tuv.com___tuv__linux__enterprise/6Superset/en/os/SRPMS" )
    input_right=$( readlink -e "${HOME}/.el-build/cache/build.ascendos.org___linux__ascendos__SRPMS" )
elif [ $# -eq 2 ]; then 
    # I don't see a particularly useful way to do something intuitive here
    usage
elif [ $# -eq 3 ]; then 
    output_file=$( readlink -f "${1}" )
    input_left=$( readlink -e "${2}" )
    input_right=$( readlink -e "${3}" )
else
    usage
fi

#############################################################################
### validate args
if [ -f "${output_file}" ]; then
    die "output file ${output_file} already exists"
fi

if [ ! -d "${input_left}" ]; then
    die "input_left directory ${input_left} does not exist"
fi

if [ ! -d "${input_right}" ]; then
    die "input_right directory ${input_right} does not exist"
fi



#############################################################################
### tmpdir
tmpdir="/tmp/tmp.${progname}.xyz.${starttime}.$$"
mkdir -p "${tmpdir}"


#############################################################################
### calculate list of modified source packages

pkg_list_left=$( ls -1A "${input_left}/"*.src.rpm | sed -e 's/.*\///g' | sort --version-sort )

pkg_list_right_all=$( ls -1A "${input_right}/"*.src.rpm | sed -e 's/.*\///g' | sort --version-sort ) 

debug "list reduction phase: remove left duplicates"
## list reduction phase: remove packages in the left set and unchanged(TODO)
pkg_list_right_modified="${pkg_list_right_all}"
for pkg in ${pkg_list_right_all}; do
    debug "checking for duplicates of ${pkg} ..."
#    debug "list reduction phase removeing packages in the left set unchanged: scanning: ${pkg}"
    # see if same named package exists in the left set
    if [ -f "${input_left}/${pkg}" ]; then
#	debug "found left set package, (TODO verify identical other than signatures)"
	# TODO: verify that rpm2cpio cpio contents match (i.e. all but sigs?)
	pkg_list_right_modified=$( listremove "${pkg}" "${pkg_list_right_modified}" )
    fi
done


for pkg in ${pkg_list_right_modified}; do
    debug "modified package list: ${pkg}"
    if ( ! echo "${pkg}" | grep -q "\.asc\..*src.rpm$" ); then
	# sigh... extra case for tuv logos off-off-spec package naming
	if ( ! echo "${pkg}" | grep -q "\.asc6\.src\.rpm$" ); then
	    die "modified bug NON .asc .src.rpm found in pkg_list_right, even after all pkg_list_left packages were removed from it."
	fi
    fi
done 


debug "list reduction phase: remove obsoleted right modified versions"

## reduce list, only interested in latest of asc.X version series
pkg_list_right_reduced="${pkg_list_right_modified}"
pkg_list_right_modified=$( listreverse "${pkg_list_right_modified}" )
# we know we are iterating in sort --version-sort(ed) order
for pkg in ${pkg_list_right_modified}; do
    debug "checking for obsoleted versions of ${pkg} ..."
    # we know this is a .asc.*src.rpm
    asc_version=$( get_asc_version "${pkg}" )

    # don't bother with .asc versions which have no lesser suffixed versions
    if ((${asc_version})); then
	for (( i=$(( ${asc_version} - 1 )) ; ${i} >= 0 ; i=$(( ${i} - 1 )) )); do
	    target_pkg=$( set_asc_version ${i} "${pkg}" )
	    pkg_list_right_reduced=$( listremove "${target_pkg}" "${pkg_list_right_reduced}" )
	done
    fi
done 

for pkg in ${pkg_list_right_reduced}; do
    debug "irreducible modified package: ${pkg}"
    echo "${pkg}" >> "${output_file}"
done 

#############################################################################
### cleanup
rm -rf "${tmpdir}"
debug "goodbye..."

### end script, only notes below...
#############################################################################
#############################################################################
#############################################################################
#
# ...



