#!/usr/bin/env bash
#
#############################################################################
#############################################################################
#
# isobuild: a complete and deterministic environment and wrapper for pungi,
#           livecd-creator, and koji distro build and compose tools.
#
#############################################################################
#
# Copyright 2011 Douglas McClendon <dmc AT filteredperception DOT org>
#
#############################################################################
#
# This file is part of X.
#
#    X is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    X is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with X.  If not, see <http://www.gnu.org/licenses/>.
#
#############################################################################
# note: if you'd like a different license, just let me know which and why
#############################################################################


#############################################################################
#############################################################################
##
## isobuild
##
##
## DESCRIPTION
##
## isobuild presumes it is run on standard pungi capable platform, e.g.
## SL60/F13/, and proceeds to generate pungi output in a thusly more easily
## reproducible fashion
##
##
## LONG TERM ROADMAP
##
## -
##
## NOTES
##
## - 
##
#############################################################################



#############################################################################
#############################################################################
##
## get runtime environment
##
starttime="$( date +%Y%m%d%H%M%S )"
progname="$( basename $0 )"
# less confusing output messages when run as embedded /tmp/x-run
progname="isobuild"
progdir=$( ( pushd $( dirname $( readlink -e $0 ) ) > /dev/null 2>&1 ; \
    pwd ; popd > /dev/null 2>&1 ) )
rundir="$( pwd )"
mypid=$$


#############################################################################
#############################################################################
##
## constant and option default definitions
##
fedora_mirror_root="ftp://ftp.linux.ncsu.edu/pub/fedora"
# 10.0.2.2 is the ip address the containing qemu-kvm uses to expose the
# host, which in this case is running apache on port 8421 as non-root
elbuild_docroot="http://10.0.2.2:8421/"
cache_root="${elbuild_docroot}/cache/"

x64outroot=/root/el-build-workarea/output
x32outroot=/var/lib/mock/mock-for-pungi-el6-i386/root/root/el-build-workarea/output
outroot=/root/output

# the f13 ones aren't going to change
# TODO: I couldn't get yumdownloader --source --config= to do what I wanted to
#       scriptedly get the latest version in the el-build wrapper's caching section
pigz_version="2.1.6-1"
mock_version="1.1.15-1"
livecdtools_version="13.4-1"

#############################################################################
#############################################################################
##
## main
##

### presumption, this is run as root from /etc/rc.d/rc.local on a system that
### has just had a min-sl60 kickstart installation (basic 'minimal' sl60 install)

# gotta start somewhere
cd /root

# keep screen from blanking (perhaps this should be in el-build only)
setterm -blank 0

# pungi requires selinux not be enforcing 
# and makeworld too, though perhaps that can be fixed
setenforce 0


mv /etc/yum.repos.d /etc/yum.repos.d.orig
mkdir /etc/yum.repos.d
cat <<EOF > /etc/yum.repos.d/sl.repo
[sl]
name=Scientific Linux \$releasever - \$basearch
# yumvars seem pretty stupid, needing to be full directory entries, i.e. this doesn't work,
# nor does \${releasever} work...
#baseurl=${cache_root}ftp.scientificlinux.org___linux__scientific__\$releasever__\$basearch__os/
baseurl=${cache_root}ftp.scientificlinux.org___linux__scientific__6.0__x86_64__os/
#mirrorlist=http://ftp.scientificlinux.org/linux/scientific/mirrorlist/sl-base-6.txt
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-sl file:///etc/pki/rpm-gpg/RPM-GPG-KEY-dawson
EOF

cat <<EOF > /etc/yum.repos.d/asc-src.repo
[asc-src]
name=Ascendos - sources
baseurl=${cache_root}build.ascendos.org___linux__ascendos__SRPMS/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ascendos-alpha file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ascendos-alpha-dmc
EOF

# sanity test of above, and workaround for a pungi bug
yumdownloader --disablerepo=* --enablerepo=asc-src --source anaconda

#cp /etc/yum.repos.d/sl.repo /etc/yum.repos.d/sl.repo.orig
# no need for updates (until an os bug requiring one hits us)
#mv /etc/yum.repos.d/sl-updates.repo /etc/yum.repos.d/sl-updates.repo.orig
#
#sed -i \
#    -e 's|http://ftp.scientificlinux.org|ftp://ftp.scientificlinux.org|g' \
#    /etc/yum.repos.d/sl.repo
#
#sed -i \
#    -e "s|ftp://ftp.scientificlinux.org/linux/scientific/\$releasever/\$basearch/os|${cache_root}ftp.scientificlinux.org___linux__scientific__\$releasever__\$basearch__os|g" \
#    /etc/yum.repos.d/sl.repo

# for rpmbuild(--rebuild)
yum -y install rpm-build

# for rebuilding pigz
yum -y install gcc
yum -y install zlib-devel

# for rpmdev-setuptree (not used) 
#yum -y install rpm-build

# for general utility 
yum -y install lftp

# for external data pulling (should already be installed
yum -y install wget

# for rebuilding python-kid
yum -y install python-docutils

# for mock
yum -y install python-decoratortools

# for rebuilding pungi
yum -y install python-devel

# for running pungi
yum -y install anaconda-runtime

# for running pungi to yield i386 media on x86_64 host
#yum -y install epel-release
#yum -y install mock
# or alternately without bringing 'all' of epel into things-

## install pubkeys for verifying .src.rpm signatures


# for yumdownloader workaround downloading of anaconda src.rpm (at least)
#wget "${ascendos_mirror_root}/GPG/RPM-GPG-KEY-ascendos-alpha"
wget "${cache_root}one-off-files/RPM-GPG-KEY-ascendos-alpha"
rpm --import RPM-GPG-KEY-ascendos-alpha
#wget "${ascendos_mirror_root}/GPG/RPM-GPG-KEY-ascendos-alpha-dmc"
wget "${cache_root}one-off-files/RPM-GPG-KEY-ascendos-alpha-dmc"
rpm --import RPM-GPG-KEY-ascendos-alpha-dmc

#wget "${fedora_mirror_root}/linux/releases/13/Everything/i386/os/RPM-GPG-KEY-fedora-13-primary"
wget "${cache_root}one-off-files/RPM-GPG-KEY-fedora-13-primary"
rpm --import RPM-GPG-KEY-fedora-13-primary
#wget "wget ftp://ftp.linux.ncsu.edu/pub/epel/RPM-GPG-KEY-EPEL-6"
wget "${cache_root}one-off-files/RPM-GPG-KEY-EPEL-6"
rpm --import RPM-GPG-KEY-EPEL-6

## TODO: make the following an loop over a list (necessarily ordered)

## get python-kid installed, needed by repoview
#wget "${fedora_mirror_root}/linux/releases/13/Everything/source/SRPMS/python-kid-0.9.6-6.fc13.src.rpm"
wget "${cache_root}one-off-files/python-kid-0.9.6-6.fc13.src.rpm"
if ( ! rpm --checksig python-kid-0.9.6-6.fc13.src.rpm ); then
    echo "${progname}: fatal error, python-kid signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild python-kid-0.9.6-6.fc13.src.rpm
rpm -Uvh /rpmbuild/RPMS/noarch/python-kid-0.9.6-6.el6.noarch.rpm

## get repoview installed, needed by pungi
#wget ${fedora_mirror_root}/linux/releases/13/Everything/source/SRPMS/repoview-0.6.5-1.fc13.src.rpm
wget "${cache_root}one-off-files/repoview-0.6.5-1.fc13.src.rpm"
if ( ! rpm --checksig repoview-0.6.5-1.fc13.src.rpm ); then
    echo "${progname}: fatal error, repoview signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild repoview-0.6.5-1.fc13.src.rpm 
rpm -Uvh /rpmbuild/RPMS/noarch/repoview-0.6.5-1.el6.noarch.rpm


## get pungi
#wget ${fedora_mirror_root}/linux/releases/13/Everything/source/SRPMS/pungi-2.0.21-1.fc13.src.rpm
# note: the f13-updates version of pungi seems to only include a single esoteric one line change
#       which seems needed if and only if some python update has also been applied (e.g. using
#       SL60__+updates__ for the bootstrap repo, which is not currently the default here)
# todo: check to see if f14/++ versions of pungi work without modification and/or have important
#       enhancements or bugfixes.  It's reasonable to start with f13 as that is likely what
#       tuv branched for its own builds (educated guess with no evidence yet to the contrary)
wget "${cache_root}one-off-files/pungi-2.0.21-1.fc13.src.rpm"
if ( ! rpm --checksig pungi-2.0.21-1.fc13.src.rpm ); then
    echo "${progname}: fatal error, pungi signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild pungi-2.0.21-1.fc13.src.rpm
rpm -Uvh /rpmbuild/RPMS/noarch/pungi-2.0.21-1.el6.noarch.rpm

## get livecd-tools for generating installable live media (livecd/dvd/usb etc) images
#wget "ftp://ftp.linux.ncsu.edu/pub/epel/6/SRPMS/livecd-tools-${livecdtools_version}.el6.src.rpm"
wget "${cache_root}one-off-files/livecd-tools-${livecdtools_version}.el6.src.rpm"
if ( ! rpm --checksig "livecd-tools-${livecdtools_version}.el6.src.rpm" ); then
    echo "${progname}: fatal error, livecd-tools signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild "livecd-tools-${livecdtools_version}.el6.src.rpm"
rpm -Uvh /rpmbuild/RPMS/x86_64/{livecd-tools,python-imgcreate}*.rpm

## get zyx-liveinstaller to support rebootless live media installation
#wget "${fedora_mirror_root}/linux/updates/13/SRPMS/zyx-liveinstaller-0.2.4-1.fc13.src.rpm"
wget "${cache_root}one-off-files/zyx-liveinstaller-0.2.4-1.fc13.src.rpm"
if ( ! rpm --checksig zyx-liveinstaller-0.2.4-1.fc13.src.rpm ); then
    echo "${progname}: fatal error, zyx-liveinstaller signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild zyx-liveinstaller-0.2.4-1.fc13.src.rpm
# TODO: use result when invoking livecd-tools 
#       /rpmbuild/RPMS/noarch/zyx-liveinstaller-0.2.4-1.el6.noarch.rpm
# TODO: post alpha, depending on consensus, only put zli in a descendent 'DescendOS' 'strain'


## get pigz installed, needed by mock
#wget ftp://ftp.linux.ncsu.edu/pub/epel/6/SRPMS/pigz-2.1.6-1.el6.src.rpm
wget "${cache_root}one-off-files/pigz-${pigz_version}.el6.src.rpm"
if ( ! rpm --checksig "pigz-${pigz_version}.el6.src.rpm" ); then
    echo "${progname}: fatal error, pigz signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild "pigz-${pigz_version}.el6.src.rpm"
rpm -Uvh "/rpmbuild/RPMS/x86_64/pigz-${pigz_version}.el6.x86_64.rpm"

## get mock installed, needed by pungi-x32(i386 output)
#wget "ftp://ftp.linux.ncsu.edu/pub/epel/6/SRPMS/mock-${mock_version}.el6.src.rpm"
wget "${cache_root}one-off-files/mock-${mock_version}.el6.src.rpm"
if ( ! rpm --checksig "mock-${mock_version}.el6.src.rpm" ); then
    echo "${progname}: fatal error, mock signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild "mock-${mock_version}.el6.src.rpm"
rpm -Uvh "/rpmbuild/RPMS/noarch/mock-${mock_version}.el6.noarch.rpm"


## run koji to generate pungi/livecd-create binary rpm input from the full dev tree

# get the full devtree
wget -O /tmp/devtree.tar.bz2 "${elbuild_docroot}devtree.tar.bz2"
mkdir /root/devtree
tar -C /root/devtree -xvf /tmp/devtree.tar.bz2

mkfs.ext3 -O sparse_super /dev/sdc
mkdir /mnt/space
mount /dev/sdc /mnt/space
mkdir /mnt/space/el-build
cp -av /root/devtree/Ascendos/6/build/koji-setup-scripts \
     /mnt/space/el-build/scripts

mkdir -p "${outroot}"
mkdir -p "${outroot}/logs"
mkdir "${outroot}/6.0"


# TODO: need to add epel or appropriate subset to offline cached mirrors
#       but for initial testing, just aiming for a first automated
#       and successful package build
yum -y install yum-conf-epel

pushd /mnt/space/el-build/scripts
bash ./makeworld
popd

# todo: fix this in makeworld
chkconfig postgresql on

# dmc: It would be my guess that it is worth 'modifying' more source packages 
#      such that this list could be reduced to ideally a single entry
dependent_bootstrap_os_list="\
sl60:http://10.0.2.2:8421/cache/ftp.scientificlinux.org___linux__scientific__6.0/\$arch/os/
f13:http://archives.fedoraproject.org:/pub/archive/fedora/linux/releases/13/Everything/\$arch/os/
f12:http://archives.fedoraproject.org:/pub/archive/fedora/linux/releases/12/Everything/\$arch/os/
rhel6beta:ftp://mirrors.kernel.org:/pub/redhat/redhat/rhel/beta/6/\arch/os/
"

# and our build repo
koji add-external-repo ascendos-build http://build.ascendos.org/linux/ascendos/build/\$arch/

bs_os_abbrevs=""
# create a build target for each dependent bootstrapping os
for dependent_bootstrap_os in ${dependent_bootstrap_os_list}; do
    os_repo=$( echo "${dependent_bootstrap_os}" | sed -e 's/[^:]*://' )
    os_abbrev=$( echo "${dependent_bootstrap_os}" | sed -e 's/:.*//' )
    bs_os_abbrevs="${bs_os_abbrevs} ${os_abbrev}"


    koji add-tag "${os_abbrev}"
    koji add-tag --arches "i686,x86_64" "${os_abbrev}-build"
    koji add-target "${os_abbrev}" "${os_abbrev}-build" "${os_abbrev}"
    koji add-group "${os_abbrev}-build" build
    # todo: obvious listification
    koji add-group-pkg "${os_abbrev}-build" build bash bzip2 coreutils cpio diffutils findutils gawk
    koji add-group-pkg "${os_abbrev}-build" build gcc gcc-c++ grep gzip info make patch redhat-rpm-config
    koji add-group-pkg "${os_abbrev}-build" build rpm-build sed shadow-utils tar unzip util-linux-ng which
    # experimental, will this work?? (instead of sl-release, fedora-release, etc
    koji add-group-pkg "${os_abbrev}-build" build system-release
    koji add-group-pkg "${os_abbrev}-build" build buildsys-macros-el6

    # create the repo
    koji add-external-repo "${os_abbrev}-base" "${os_repo}"
    # cause it to be used for builds with abbrev-build build tag (src or dest, I forget)
    koji add-external-repo "${os_abbrev}-base" -t "${os_abbrev}-build"
    # cause the ascendos-build repo to be used for each of the build-targets
    koji add-external-repo ascendos-build -t "${os_abbrev}-build"
done

# todo, this repo needs to get generated from the new gen-tdv-srpm-repo script, and the list
# with the reverse builddate sorting
srpm_list=$( lftp -e "cd cache ; cd build.ascendos.org___linux__ascendos__SRPMS ; ls ; quit" http://10.0.2.2:8421/ 2>&1 | awk '{print $5}' | grep "\.src\.rpm$" | sort --sort=version )
echo "${srpm_list}" > "${outroot}/logs/koji_tobuild_srpm_list.txt"

# FIXME:initial dev/debug
srpm_list="\
libXfixes-4.0.4-1.el6.src.rpm
"

mkdir "${outroot}/koji"

pkg_list=""
for srpm in ${srpm_list}; do
    pkg_nvr=$( basename "${srpm}" .src.rpm )
    pkg_nv=$( "${pkg_nvr}" | sed -e 's/-[^-]*$//' )
    pkg_n=$( "${pkg_nv}" | sed -e 's/-[^-]*$//' )
    # better to do this with a local copy of the package and rpm query with format
    pkg_list="${pkg_list} ${pkg_n}"

    # does it matter that this isn't choosing initial tag/target
    # based on what they end up getting built against?
    koji add-pkg --owner=ascendos-team sl60 "${pkg_n}"
done

#
# BIG NOTE: this here is just the crudest first pass at a completely 
#           automated build.  Interesting questions such as whether a 6.1 update
#           should be built against the 6.0 output, or more importantly, if all
#           the 6.0 output should be rebuilt against itself, are currently left
#           as topics for further discussion and solidification as automation logic.
#           myself, I'd prefer, if it turned out to be possible/feasible/practical,
#           to make enough package changes that a bootstrap from _just_ f13, _or_
#           centos5x was possible.  But that is all post-beta fodder if not post 
#           main release.
#
#           What is here for this first pass represents what I think Troy expected
#           would work as a general algorithm.  I.e. try sl60, then f13, then f12,
#           then rhel6beta, and if one of those latter ones works, that is fine to
#           use instead of alternately trying to modify the src.rpm.  Personally,
#           it just feels wrong to me mixing binaries built against these radically
#           different buildroots, but I'll grant the best path is to get that full
#           working as a deployable release to the masses, and if desired, worrying
#           about simplified bootstrapping post-release.  Or the quite real possibility
#           that as I grok things better, it wil radically change my impression of
#           where the code should end up at.
#
#           Also, I think Troy with the existing build.ascendos.org/koji had packages
#           feeding back into the koji-external-repos, unlike here.  That gets to 
#           the question above, and if strongly desired could be added here.  Though
#           that seems to me to be very wonky, as envisioned by the case of dozens
#           of koji build nodes, and trying to spawn hundreds of new package updates
#           simultaneously, and i.e. the nondeterminism in the contents of their
#           buildroots based on what other packages had finished before they started.
#           Or I could still totally be misunderstanding something subtle (or even 'obvious')
#
#

pushd  "${outroot}/koji"

for srpm in ${srpm_list}; do
    xdone=0
    for bs_os in ${bs_os_abbrevs}; do
	echo "DEBUG: about to try building ${srpm} against ${bs_os} ..."
	wget "http://10.0.2.2:8421/cache/build.ascendos.org___linux__ascendos__SRPMS/${srpm}"
	if $( koji build "${bs_os}" "${srpm}" ); then
	    rm -f "${srpm}"
	    pkg_nvr=$( basename "${srpm}" .src.rpm )
	    koji download-build "${pkg_nvr}"
	    echo "DEBUG: seemed to build ok..."
	else
	    echo "DEBUG: seemed NOT to build ..."
	fi
    done
done

popd

# TODO: iterate over input packages and use el-push to arrange into
#       an output structure suitable for pungi here below (instead of 
#       its current use of published builds

## run pungi non-mock for x86_64 (TODO: may as well run it under mock for consistency)
mkdir /root/el-build-workarea
mkdir /root/el-build-workarea/cache
mkdir /root/el-build-workarea/output

# TODO: see if there is a better pungi kickstart to start from in the spin-kickstarts
#       package, versus the one currently being based on from the pungi package itself.

# TODO: share pungi arch kickstarts with %include and ksflatten 

pungi \
    --cachedir=/root/el-build-workarea/cache \
    --destdir=/root/el-build-workarea/output \
    --name=Ascendos \
    --ver=6.0 \
    --bugurl=http://bugzilla.ascendos.org \
    --fulltree \
    --selfhosting \
    --nosplitmedia \
    --config="${elbuild_docroot}pungi-x86_64.ks"

# save space for now (same thing theoretically made later for i386 run)
rm -rvf /root/el-build-workarea/output/*/source/SRPMS \
    > /root/el-build-workarea/output/deleted.x86_64.SRPMS.txt

adduser xmock
usermod -a -G mock xmock
wget -O /etc/mock/mock-for-pungi-el6-i386.cfg \
    "${elbuild_docroot}mock-for-pungi-el6-i386.cfg"

su - xmock -c "mock -r mock-for-pungi-el6-i386 --init"
su - xmock \
    -c "mock -r mock-for-pungi-el6-i386 --no-clean --install wget"
su - xmock \
    -c "mock -r mock-for-pungi-el6-i386 --no-clean --install anaconda-runtime"
mkdir -p /var/lib/mock/mock-for-pungi-el6-i386/root/root
mkdir -p /var/lib/mock/mock-for-pungi-el6-i386/root/root/el-build-workarea
mkdir -p /var/lib/mock/mock-for-pungi-el6-i386/root/root/el-build-workarea/cache
# share the prior x86_64 cache with the i386 under mock run
#  - should save a few hours time.  Probably a few more can be
#    saved by using non-usermode qemu/kvm networking if available,
#    or alternately just transferring the cache once as a tar file 
#    image attached as disk.  And then also using any available free
#    lvm space for disks instead of qemu-img ones.  But like I said,
#    for 6x-alpha, not yet a high priority.
mount --bind \
    /root/el-build-workarea/cache \
    /var/lib/mock/mock-for-pungi-el6-i386/root/root/el-build-workarea/cache
mkdir -p /var/lib/mock/mock-for-pungi-el6-i386/root/root/el-build-workarea/output
cp -av /rpmbuild/RPMS/noarch/python-kid-0.9.6-6.el6.noarch.rpm \
    /var/lib/mock/mock-for-pungi-el6-i386/root/root/
su - xmock \
    -c "mock -r mock-for-pungi-el6-i386 --no-clean --shell '\
rpm -Uvh /root/python-kid-\*.rpm'"
cp -av /rpmbuild/RPMS/noarch/repoview-0.6.5-1.el6.noarch.rpm \
    /var/lib/mock/mock-for-pungi-el6-i386/root/root/
su - xmock \
    -c "mock -r mock-for-pungi-el6-i386 --no-clean --shell '\
rpm -Uvh /root/repoview-\*.rpm'"
cp -av /rpmbuild/RPMS/noarch/pungi-2.0.21-1.el6.noarch.rpm \
    /var/lib/mock/mock-for-pungi-el6-i386/root/root/
su - xmock \
    -c "mock -r mock-for-pungi-el6-i386 --no-clean --shell '\
rpm -Uvh /root/pungi-\*.rpm'"



# note sure about what works for multilinebreaking here, too tired to care
su - xmock \
    -c "mock -r mock-for-pungi-el6-i386 --verbose --no-clean --chroot '\
pungi \
  --cachedir=/root/el-build-workarea/cache \
  --destdir=/root/el-build-workarea/output \
  --name=Ascendos \
  --ver=6.0 \
  --bugurl=http://bugzilla.ascendos.org \
  --fulltree \
  --selfhosting \
  --nosplitmedia \
  --config=${elbuild_docroot}pungi-i386.ks'" 

# undo the bind mount
umount /var/lib/mock/mock-for-pungi-el6-i386/root/root/el-build-workarea/cache

mkdir /root/el-build-workarea
mkdir /root/el-build-workarea/cache
mkdir /root/el-build-workarea/tmp
## first livecd invocation, just minimal test for now
pushd /root/el-build-workarea
wget "${elbuild_docroot}livecd-desktop-i386.ks"
## install rebootless installation goodness
cat <<EOF >> "livecd-desktop-i386.ks"
%post --nochroot
rpm --root \$INSTALL_ROOT -Uvh /rpmbuild/RPMS/noarch/zyx-liveinstaller-0.2.4-1.el6.noarch.rpm
sed -i -e "s/fedora-release/ascendos-release/g" \$INSTALL_ROOT/usr/sbin/zyx-liveinstaller-cli
echo "Ascendos Alpha RuleZ" > \$INSTALL_ROOT/etc/zyx-liveinstaller.install.txt
# on 6.0-alpha zli seems very slow, no need to clutter apps menu with this very,
# alpha/experimental tool.  But still, nice to have as an option from the cli
rm -f \$INSTALL_ROOT/usr/share/applications/zyx-liveinstaller.desktop
EOF
livecd-creator \
    --verbose \
    --cache=/root/el-build-workarea/cache \
    --tmpdir=/root/el-build-workarea/tmp \
    --logfile=/root/el-build-workarea/livecd-desktop-x32.log \
    --fslabel="asc60_livecd_desktop_x32" \
    --config=livecd-desktop-i386.ks
mv asc60_livecd_desktop_x32.iso \
    "${x32outroot}/6.0/i386/iso/Ascendos-6.0-i386-LiveCD-Desktop.iso"
mv /root/el-build-workarea/livecd-desktop-x32.log \
    "${outroot}/logs/"
mv /root/el-build-workarea/livecd-desktop-i386.ks \
    "${outroot}/logs/"

wget "${elbuild_docroot}livecd-desktop-x86_64.ks"
## install rebootless installation goodness
cat <<EOF >> "livecd-desktop-x86_64.ks"
%post --nochroot
cp /rpmbuild/RPMS/noarch/zyx-liveinstaller-0.2.4-1.el6.noarch.rpm \$INSTALL_ROOT/tmp/zyx-liveinstaller-0.2.4-1.el6.noarch.rpm
chroot \$INSTALL_ROOT rpm -Uvh /tmp/zyx-liveinstaller-0.2.4-1.el6.noarch.rpm
rm -f \$INSTALL_ROOT/tmp/zyx-liveinstaller-0.2.4-1.el6.noarch.rpm
sed -i -e "s/fedora-release/ascendos-release/g" \$INSTALL_ROOT/usr/sbin/zyx-liveinstaller-cli
echo "Ascendos Alpha RuleZ" > \$INSTALL_ROOT/etc/zyx-liveinstaller.install.txt
# on 6.0-alpha zli seems very slow, no need to clutter apps menu with this very,
# alpha/experimental tool.  But still, nice to have as an option from the cli
rm -f \$INSTALL_ROOT/usr/share/applications/zyx-liveinstaller.desktop
EOF
livecd-creator \
    --verbose \
    --cache=/root/el-build-workarea/cache \
    --tmpdir=/root/el-build-workarea/tmp \
    --logfile=/root/el-build-workarea/livecd-desktop-x64.log \
    --fslabel="asc60_livecd_desktop_x64" \
    --config=livecd-desktop-x86_64.ks
mv asc60_livecd_desktop_x64.iso \
    "${x64outroot}/6.0/x86_64/iso/Ascendos-6.0-x86_64-LiveCD-Desktop.iso"
mv /root/el-build-workarea/livecd-desktop-x64.log \
    "${outroot}/logs/"
mv /root/el-build-workarea/livecd-desktop-x86_64.ks \
    "${outroot}/logs/"
popd



mkdir -p "${outroot}"
mkdir "${outroot}/6.0"

# .composeinfo
mv "${x64outroot}/6.0/.composeinfo" \
    "${outroot}/6.0/.composeinfo.x86_64"
mv "${x32outroot}/6.0/.composeinfo" \
    "${outroot}/6.0/.composeinfo.i386"

# logs
mkdir "${outroot}/logs"
mv "${x64outroot}/logs/"* \
    "${outroot}/logs/"
mv "${x32outroot}/logs/"* \
    "${outroot}/logs/"
mv "${x64outroot}/deleted.x86_64.SRPMS.txt" \
    "${outroot}/logs/"
mv /root/anaconda-ks.cfg \
    "${outroot}/logs/build-host.anaconda-ks.cfg"
mv /root/install.log \
    "${outroot}/logs/build-host.install.log"
mv /root/install.log.syslog \
    "${outroot}/logs/build-host.install.log.syslog"
cp /root/x-run.log \
    "${outroot}/logs/x-run.partial.log"

# work
mkdir "${outroot}/work"
mv "${x64outroot}/work/"* \
    "${outroot}/work/"
mv "${x32outroot}/work/"* \
    "${outroot}/work/"

# main stuffs
mv "${x64outroot}/6.0/x86_64" \
    "${outroot}/6.0/"
mv "${x32outroot}/6.0/i386" \
    "${outroot}/6.0/"

# sources
mv "${x32outroot}/6.0/source" \
    "${outroot}/6.0/"

# bug workaround (TODO a bit cleaner after the first test)
cp /root/anaconda*.src.rpm \
    "${outroot}/6.0/source/SRPMS/"


# prepare output for the external user
if [ -f /tmp/disk-sdb-is-going-to-get-overwritten ]; then
    cd "${outroot}"
    tar -cvf /dev/sdb . 
fi

# done

#############################################################################
## end script - only notes below
#############################################################################
#
#



