#!/usr/bin/env bash


### presumption, this is run as root from /etc/rc.d/rc.local on a system that
### has just had a min-sl60-x64 kickstart installation (basic 'minimal' sl60 install)

# gotta start somewhere
cd /root

# pungi requires selinux not be enforcing
setenforce 0

# for rpmbuild(--rebuild)
yum -y install rpm-build

# for rpmdev-setuptree (not used) 
#yum -y install rpm-build

# for general utility (not used)
#yum -y install lftp

# for external data pulling (should already be installed
yum -y install wget

# for rebuilding python-kid
yum -y install python-docutils

# for rebuilding pungi
yum -y install python-devel

# for running pungi
yum -y install anaconda-runtime

# for running pungi to yield i386 media on x86_64 host
yum -y install epel-release
yum -y install mock

# trust the f13 key, to verify pungi/repoview/...
cat <<EOF > RPM-GPG-KEY-fedora-13-primary
-----BEGIN PGP PUBLIC KEY BLOCK-----                                                  
Version: GnuPG v1.4.5 (GNU/Linux)

mQINBEtWPNwBEADjDowYLqGZJevWtPil9jpwrN2gUE5YdKSpdN+FmeS4PaBjM293
O56WY1vElOFbD/wO0+UsYsSU3J+Wfz/6hNnC953mNN4d6luT2tMs0Qc5LZ4Xmsod
a5BWlr1tASUBA/DPiS1mtdKm3n6WuW3fZYydRK2EBskv9tuA3LKgmm9e9OcbTJjC
lUdtw7868WqR2aU383l9G9HPoN6aR4EKgNgSefdNPTsxD04xbLo/aSHAG85fvXmg
2z2sVOw3v2oEALCIaL0QPWZ3gcCyY+FUmF8fWofSEqnHWhdrmbqvsitX+BGWte5o
F0M5m1JIDIBu7JxEeB0t0ZNoeZnWBWsXTY50qUSZjLRSsgkiSNaaaEAOvu4TJe79
B6xfv8zn2P98lnBEuuAH5GtFsAAf/7htchKbQ72ePGLjIow4BSAr2ZTIhaRnrd6v
fKSZsL0lKp8rutUTYncm/EM6xB+fApf+BlDtsw2HWZqi14ADGM8pVOwq4rwhWWFd
em9pGosy4fW8Oug0T+WIXmYx3TRh1o2U7kBDrKUqZu6Gm57YFAAARPjgeg0Pu5+P
JEtRinhfm57s6YieefzBY/rha48sWk5jbXFKqbOCNInE9rerWnpscvSVaIhGQZYW
Za3FGhjAHU5ZEDVHT+du5X+aKqj2NZmi+5G/DBg2322d0++exyRHIU//6QARAQAB
tCZGZWRvcmEgKDEzKSA8ZmVkb3JhQGZlZG9yYXByb2plY3Qub3JnPokCNgQTAQIA
IAUCS1Y83AIbDwYLCQgHAwIEFQIIAwQWAgMBAh4BAheAAAoJEH7catbo5A/egacP
/1rDtOD5YhVhxJr2rcVyMF0yFERtRVP+nb4vb5HGxms6C4nI8b0jYwLe/OAkdS5g
xdw+MVKVx1RcnN83N5YBwcCJiNiaN/SXUb+SbIWNCbfZq0s7jm9OWtZLE+WRkY8F
NKfogR+rd27YfkdI+Y/5at4e9J0c6HyiczNMfUaahZhl+XeodZwaGdjhNpiKD/LC
V/Ouhq46HUEuos5bHtk2Pz+1EUhsCuih/eeIHU2bRtRGjYF9jGffs4O9b+G/QfI2
42IDoNqVotyLndiJBiR67iUGG8NLYARi9sDeD+B7pQ1b+LptYq1ltn4/3gbngKza
SqXFdcjx2SOjpRPOGRc/pPchoAOZS2dYr8aSVkwc6A0VRLb8FGLaVkQa3o0eAq/N
95wCE9XSFtGWIiCLjsygrTaXjOKdLzOAhaShk4KOdD2phHQ+cwz/Z9fDvtAozPvQ
o36uB0d6Y1mdDjCmtfNfYTumL1z40/evLOlLXadQjY/+GoidBh+BotSCAeQLAMMH
+yDaTBFhUIER76OVfpMTja2D2s5YmcD01LhLF4Q3DsfNCSiwe8vhiN1KzyVnrwJi
T6HwcX68lc0zXhIOADUohs950Drm3btOJP0vZTc0KT8Bvxy/ru+vkdFoqUL3Cw54
g9fxqLowt3WXdBXuTdM9wlrBXXrSLpGFuuiv4Yzo2u3Q
=0lqj
-----END PGP PUBLIC KEY BLOCK-----
EOF

# ... instead of trusting there is no MITM between us and the source
#wget ftp://ftp.linux.ncsu.edu/pub/fedora/linux/releases/13/Everything/i386/os/RPM-GPG-KEY-fedora-13-primary
rpm --import RPM-GPG-KEY-fedora-13-primary

## get python-kid installed, needed by repoview (needed by pungi)
wget ftp://ftp.linux.ncsu.edu/pub/fedora/linux/releases/13/Everything/source/SRPMS/python-kid-0.9.6-6.fc13.src.rpm
if ( ! rpm --checksig python-kid-0.9.6-6.fc13.src.rpm ); then
    echo "asc-isobuild: fatal error, python-kid signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild python-kid-0.9.6-6.fc13.src.rpm
rpm -Uvh /root/rpmbuild/RPMS/noarch/python-kid-0.9.6-6.el6.noarch.rpm

## get repoview installed, needed by pungi
wget ftp://ftp.linux.ncsu.edu/pub/fedora/linux/releases/13/Everything/source/SRPMS/repoview-0.6.5-1.fc13.src.rpm
if ( ! rpm --checksig repoview-0.6.5-1.fc13.src.rpm ); then
    echo "asc-isobuild: fatal error, repoview signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild repoview-0.6.5-1.fc13.src.rpm 
rpm -Uvh /root/rpmbuild/RPMS/noarch/repoview-0.6.5-1.el6.noarch.rpm


## get pungi
wget ftp://ftp.linux.ncsu.edu/pub/fedora/linux/releases/13/Everything/source/SRPMS/pungi-2.0.21-1.fc13.src.rpm
if ( ! rpm --checksig pungi-2.0.21-1.fc13.src.rpm ); then
    echo "asc-isobuild: fatal error, pungi signature could not be verified as correct"
    exit 1
fi
rpmbuild --rebuild pungi-2.0.21-1.fc13.src.rpm
rpm -Uvh /root/rpmbuild/RPMS/noarch/pungi-2.0.21-1.el6.noarch.rpm

## run pungi non-mock for x86_64 (TODO: may as well run it under mock for consistency)
mkdir /root/pungi-workarea
mkdir /root/pungi-workarea/cache
mkdir /root/pungi-workarea/output

# TODO: yuminst git, and git clone Asc tree, to get 

pungi \
    --cachedir=/root/pungi-workarea/cache \
    --destdir=/root/pungi-workarea/output \
    --name Ascendos \
    --bugurl=http://bugzilla.ascendos.org \
    --fulltree \
    --selfhosting \
    --nosplitmedia \
    --config=/root/pungi-workarea/pungi-x86_64.ks
